---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdc-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sdc"
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  labels:
    app: datacollector
spec:
  ports:
  - port: 18630
    targetPort: 18630
    name: ui
  clusterIP: None
  selector:
    app: datacollector
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: datacollector
spec:
  serviceName: "datacollector"
  replicas: 1
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: datacollector
        image: kubeworks/sdc:dev
        ports:
        - containerPort: 18630
          name: ui
        readinessProbe:
          exec:
            command: ["curl", "127.0.0.1:18630/public-rest/ping"]
        volumeMounts:
        - name: sdc-pvc
          mountPath: /data
          subPath: data
  volumeClaimTemplates:
  - metadata:
      name: sdc-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

